import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import NavbarMobile from '@/components/navbar/NavbarMobile';
import Footer from '@/components/footer/Footer';
import TanstackProvider from '@/providers/TanstackProvider';
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <NavbarMobile />
        <ToastContainer />
        <TanstackProvider>
          <div style={{ minHeight: '100vh' }}>
            {children}
          </div>
        </TanstackProvider>
        <Footer />
      </body>
    </html>
  );
}
