import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { ReduxProvider } from "@/app/providers/ReduxProvider";
import TanStackProvider from "@/app/providers/TanStackProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Konserin.com",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex justify-center'>
        <div className='container w-[500px] min-w-[500px] max-w-[500px]'>
          
          <TanStackProvider>
          <Header />
          {children}
          <Footer />
          </TanStackProvider>
          
        </div>
      </body>
    </html>
  );
}
